"use client"

import { useEffect } from "react"
import { createSupabaseBrowserClient } from "@/lib/supabase"

/**
 * Client-side OAuth callback handler.
 *
 * Why client-side instead of a Route Handler?
 * The PKCE code_verifier is generated by the browser client and may be stored
 * in localStorage or a browser-managed cookie. A server-side Route Handler
 * running in a Vercel edge function can't reliably access that verifier.
 * Running the exchange in the browser ensures all PKCE state is available.
 */
export default function AuthCallbackPage() {
  useEffect(() => {
    const supabase = createSupabaseBrowserClient()

    const run = async () => {
      const url = new URL(window.location.href)
      const code = url.searchParams.get("code")
      const rawNext = url.searchParams.get("next") ?? "/backoffice/dashboard"

      // Prevent open redirects — next must be a relative path
      const next =
        rawNext.startsWith("/") && !rawNext.startsWith("//")
          ? rawNext
          : "/backoffice/dashboard"

      if (code) {
        const { error } = await supabase.auth.exchangeCodeForSession(code)
        if (error) {
          console.error("[auth/callback] exchangeCodeForSession error:", error.message)
          window.location.replace("/login?error=auth_callback_error")
          return
        }
      }

      // Verify session exists after exchange
      const { data: { session }, error: sessionError } = await supabase.auth.getSession()

      if (sessionError || !session) {
        console.error("[auth/callback] no session after exchange:", sessionError?.message)
        window.location.replace("/login?error=auth_callback_error")
        return
      }

      // Persist Google provider tokens server-side so automations can use them
      if (session.provider_token && session.user?.email) {
        await fetch("/api/auth/save-google-tokens", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            access_token: session.provider_token,
            refresh_token: session.provider_refresh_token ?? null,
          }),
        }).catch((err) => console.error("[auth/callback] save-google-tokens error:", err))
      }

      // Full page navigation so the middleware reads the fresh session cookies
      window.location.replace(next)
    }

    run()
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="min-h-screen bg-background flex items-center justify-center">
      <div className="flex flex-col items-center gap-3">
        <div className="w-6 h-6 border-2 border-accent-blue border-t-transparent rounded-full animate-spin" />
        <p className="text-text-muted text-sm">Iniciando sesión...</p>
      </div>
    </div>
  )
}
